[project]
name = "flexster"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.0.0",
    "qrcode>=8.2",
    "requests>=2.31.0",
    "reportlab>=4.0.0",
]
